### ISSUE TITLE
In Windows 10 it doesn't work

### ISSUE THREAD

**Issue by UnEnanoMas** [Blugin/ChatThin-PMMP#1] opened 2020-07-24 19:34 UTC
Windows 10 screenshot:

![Captura de pantalla (136)](https://user-images.githubusercontent.com/63286108/88428494-4b2ad000-cdf5-11ea-8a96-02f93f75c158.png)

Phone screenshot:

![IMG_20200724_213051](https://user-images.githubusercontent.com/63286108/88428547-61d12700-cdf5-11ea-9fd2-ecabf4a0ed8a.jpg)

**Comment by PresentKim** [comment] 2020-07-25 04:02
The demo screenshot I uploaded was also taken in the Windows 10 edition.
If the plugin that colors the chat in use on the server is a deployed plugin, can you give me a link?
I'll test plugin with that plugin

**Comment by PresentKim** [comment] 2020-07-25 05:11
I found the cause!
There was a problem with the functionality of this plugin not working properly when users used the Noto sans font.
I applied this feature using a different word, and now it works fine.

I resolved this issue in #2.
This has been fixed in version [1.0.1](https://github.com/Blugin/ChatThin-PMMP/releases/tag/1.0.1).
![_](https://i.ibb.co/VYrdLmC/image.png)

**Closed as completed by PresentKim** 2020-07-25 05:11 UTC
